# Generated by Django 4.1.7 on 2023-05-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='title',
            field=models.CharField(default='Ошибка', max_length=40),
        ),
    ]
