# Generated by Django 4.1.7 on 2023-05-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_list_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='bg',
            field=models.ImageField(default='Ошибка', upload_to='bg/'),
        ),
    ]
