# Generated by Django 4.1.7 on 2023-06-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_list_audio_tracks_remove_list_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='bg',
        ),
        migrations.RemoveField(
            model_name='list',
            name='description',
        ),
        migrations.AddField(
            model_name='list',
            name='audio_tracks',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='list',
            name='country',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='list',
            name='director',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='list',
            name='premiere',
            field=models.DateField(default='2010-01-01'),
        ),
        migrations.AddField(
            model_name='list',
            name='subtitles',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='list',
            name='title',
            field=models.CharField(default='None', max_length=40),
        ),
    ]
