# Generated by Django 4.1.7 on 2023-06-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_list_bg_remove_list_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='season',
            field=models.CharField(default='winter', max_length=8),
        ),
    ]
