# Generated by Django 4.1.7 on 2023-06-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_list_genre_list_studio_alter_list_season_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='sorting',
            field=models.CharField(default='special', max_length=50),
        ),
    ]
