# Generated by Django 4.1.7 on 2023-06-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_list_sorting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='sorting',
            field=models.CharField(default='all', max_length=50),
        ),
    ]
