# Generated by Django 4.1.7 on 2023-06-15 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_list_necessarily'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='necessarily',
        ),
    ]
